name: tajna
version: 0.0.0.0
synopsis: Local 12factor environments.
description: |
  Run your 12factor apps locally.
  .
  @
  tajna run
  @
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/tajna
category: Development
tested-with: GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base >=4.7 && <4.10
- aeson
- base-compat
- bytestring
- Cabal
- directory
- DRBG
- exceptions
- lens
- monadcryptorandom
- optparse-applicative
- process
- process-extras
- regex-applicative-text
- text
- transformers
- unordered-containers
- vector
- yaml >=0.8.14

executables:
  tajna:
    main: Main.hs
    source-dirs: src
